### ISSUE TITLE
[BUG] _auth not work for internal registry based off information (lack of?) found on docs.npmjs.com 

### ISSUE THREAD

**Issue by rcampbel** [npm/config#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using an internal registry as a repository and proxy publish fails due to auth errors because the registry in the .npmrc does not match the registry in the `package.json` `publishConfig`

Error:
```
user@rcampbe-mac WebContent % npm install
npm ERR! code E401
npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
npm ERR! A complete log of this run can be found in:
npm ERR! /Users/user/.npm/_logs/2022-02-10T22_35_37_017Z-debug.log
user@user-mac dir %
```

### Expected Behavior

the _auth property defined in .npmrc used for the repository where package will be published.

AND/OR

Documentation (https://docs.npmjs.com/cli/v8/using-npm/config) updated to reflect that if using an internal register and internal proxy register how the configuration for the different registries should be accomplished.  This should probably include which properties are configurable for the different registries

### Steps To Reproduce

Note the follow is assuming that you already have a private npm repository set up to both store internally created modules and a proxy to the global npm repository for modules not in the repository.

1) config .npmrc:
```
init-author-name=Some Name
init-author-email=Some_Name@company.com
init-author-url=https://company.com
email=Some_Name@company.com
registry='http://company.com/interalRepoProxy'
_auth=${COMPANY_INTERNAL_REPO_AUTH}
fund=false
package-lock=true
```

2) config package.json:
```
{
  "name": "the-package",
  "version": "1.0.0",
  "description": "Test package.json",
  "publishConfig": {
    "registry": "http://company.com/interalRepo"
  },
  "author": "company.com",
  "license": "ISC"
}
```

3) run `npm publish`

### Environment

- npm: 8.5.1
- Node: v16.13.1
- OS: Mac
- platform: Macbook pro
---
- npm: 8.5.1
- Node: v16.13.1
- OS: Node v16.13.1 Docker image
- platform: Gitlab Docker Image Runner

**Comment by rcampbel** [comment]
Note I was able to fix my issue by adding the publishConfig.registry followed by the _auth value to fix this issue
```
//company.com/interalRepo/:=_auth=${COMPANY_INTERNAL_REPO_AUTH}
```

I did not find this information anywhere on the docs.npmjs.com site, had to dive into the npm code and node_modules included by npm to find this.

**Comment by jenseng** [comment]
Seems like the docs need to be updated, I believe this functionality was removed in NPM 7, [see here](https://github.com/npm/npm-registry-fetch/commit/cc11cc15c9f457c01159a69ce342dc99dea12456) for some more context.

**Comment by rcampbel** [comment]
@jenseng after reading the information in the link, if I understand it right, it sounds like this part might not be working

> The npm cli will automatically scope these top-level
  configs to the default registry option and save them back to the
  `.npmrc` file the first time they are encountered, so users generally
  see no disruption, and this change only affects non-npm users of
  npm-registry-fetch.

**Comment by wraithgar** [comment]
npm no longer accepts a bare `_auth` config, all auth related config needs to be targeted to a specific registry.
